/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApuRouteImport } from './routes/apu'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ContabilidadRouteImport } from './routes/contabilidad'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FotografiasRouteImport } from './routes/fotografias'
import { Route as PresupuestoRouteImport } from './routes/presupuesto'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as UsuariosRouteImport } from './routes/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApuRoute = ApuRouteImport.update({
  id: '/apu',
  path: '/apu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadRoute = ContabilidadRouteImport.update({
  id: '/contabilidad',
  path: '/contabilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografiasRoute = FotografiasRouteImport.update({
  id: '/fotografias',
  path: '/fotografias',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoRoute = PresupuestoRouteImport.update({
  id: '/presupuesto',
  path: '/presupuesto',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apu': typeof ApuRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contabilidad': typeof ContabilidadRoute
  '/cronograma': typeof CronogramaRoute
  '/documentos': typeof DocumentosRoute
  '/fotografias': typeof FotografiasRoute
  '/presupuesto': typeof PresupuestoRoute
  '/proyectos': typeof ProyectosRoute
  '/reportes': typeof ReportesRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apu': typeof ApuRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contabilidad': typeof ContabilidadRoute
  '/cronograma': typeof CronogramaRoute
  '/documentos': typeof DocumentosRoute
  '/fotografias': typeof FotografiasRoute
  '/presupuesto': typeof PresupuestoRoute
  '/proyectos': typeof ProyectosRoute
  '/reportes': typeof ReportesRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apu': typeof ApuRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contabilidad': typeof ContabilidadRoute
  '/cronograma': typeof CronogramaRoute
  '/documentos': typeof DocumentosRoute
  '/fotografias': typeof FotografiasRoute
  '/presupuesto': typeof PresupuestoRoute
  '/proyectos': typeof ProyectosRoute
  '/reportes': typeof ReportesRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apu'
    | '/configuracion'
    | '/contabilidad'
    | '/cronograma'
    | '/documentos'
    | '/fotografias'
    | '/presupuesto'
    | '/proyectos'
    | '/reportes'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apu'
    | '/configuracion'
    | '/contabilidad'
    | '/cronograma'
    | '/documentos'
    | '/fotografias'
    | '/presupuesto'
    | '/proyectos'
    | '/reportes'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/apu'
    | '/configuracion'
    | '/contabilidad'
    | '/cronograma'
    | '/documentos'
    | '/fotografias'
    | '/presupuesto'
    | '/proyectos'
    | '/reportes'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApuRoute: typeof ApuRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ContabilidadRoute: typeof ContabilidadRoute
  CronogramaRoute: typeof CronogramaRoute
  DocumentosRoute: typeof DocumentosRoute
  FotografiasRoute: typeof FotografiasRoute
  PresupuestoRoute: typeof PresupuestoRoute
  ProyectosRoute: typeof ProyectosRoute
  ReportesRoute: typeof ReportesRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apu': {
      id: '/apu'
      path: '/apu'
      fullPath: '/apu'
      preLoaderRoute: typeof ApuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad': {
      id: '/contabilidad'
      path: '/contabilidad'
      fullPath: '/contabilidad'
      preLoaderRoute: typeof ContabilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografias': {
      id: '/fotografias'
      path: '/fotografias'
      fullPath: '/fotografias'
      preLoaderRoute: typeof FotografiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto': {
      id: '/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof PresupuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApuRoute: ApuRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ContabilidadRoute: ContabilidadRoute,
  CronogramaRoute: CronogramaRoute,
  DocumentosRoute: DocumentosRoute,
  FotografiasRoute: FotografiasRoute,
  PresupuestoRoute: PresupuestoRoute,
  ProyectosRoute: ProyectosRoute,
  ReportesRoute: ReportesRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
